apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-frontend
  template:
    metadata:
      labels:
        app: react-frontend
    spec:
      containers:
        - name: react-frontend
          image: toanelnino1902/react-frontend:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: react-frontend
spec:
  selector:
    app: react-frontend
  ports:
    - protocol: TCP
      port: 80         # Cổng mà dịch vụ lắng nghe
      targetPort: 80    # Cổng trong container mà dịch vụ truy cập
      nodePort: 30930   # Cổng sẽ được expose ra ngoài
  type: NodePort       # Đảm bảo dịch vụ là NodePort để có thể truy cập từ bên ngoài
